# makefile for QKC

CC     = cl
BIND   = cl
CFLAGS = /AC /Gs /Oeilt
LFLAGS = /Feqkc.com $(CFLAGS)
OBJ    = qkc.obj qkcconv.obj qkcexec.obj qkchelp.obj qkcopt.obj qkctbl.obj

.c.obj:
	$(CC) $(CFLAGS) /c $<

qkc.com: $(OBJ)
	$(BIND) $(LFLAGS) $(OBJ)

$(OBJ): qkc.h

clean:
	del *.obj
	del qkc.com
