# makefile for QKC

CC      = lcc
BIND    = lcc
CFLAGS  = -DLSI_C -O
LFLAGS1 = -o qkc.co_ $(CFLAGS)
LFLAGS2 = -ltinymain.obj
OBJ     = qkc.obj qkcconv.obj qkcexec.obj qkchelp.obj qkcopt.obj qkctbl.obj

.c.obj:
	$(CC) $(CFLAGS) -c $<

qkc.com : qkc.co_
	copy /b qkc.co_ qkc.com

qkc.co_ : $(OBJ)
	$(BIND) $(LFLAGS1) $(OBJ) $(LFLAGS2)

$(OBJ) : qkc.h

clean:
	del *.obj
	del qkc.co_
	del qkc.com
