# makefile for QKC

CC     = bcc
BIND   = bcc
CFLAGS = -a -d -G -k- -mc -n -O -p -Z
LFLAGS = -eqkc.com $(CFLAGS)
OBJ    = qkc.obj qkcconv.obj qkcexec.obj qkchelp.obj qkcopt.obj qkctbl.obj

.c.obj:
	$(CC) $(CFLAGS) -c $<

qkc.com: $(OBJ)
	$(BIND) $(LFLAGS) $(OBJ)

$(OBJ): qkc.h

clean:
	del *.obj
	del qkc.com
