.TH QKC 1 "1995年10月1日"
.SH 【名前】
QKC \- Quick KANJI code Converter  C Version 1.0
.SH 【書式】
qkc [options] [filenames]
.br
qkc \-nkf [options] [filenames] 《nkfエミュレーションモード》
.SH 【説明】
日本語の文字コード体系として、現在主に JISコード、シフトJISコード、EUCの3種
類の漢字コードがあり、UNIXではEUCとJISコードが、MS-DOSやMS-Windowsではシ
フトJISコードがよく用いられています。『QKC』はテキストファイル中のそれら
の漢字コードを相互に変換します。
.PP
filenamesは1個以上のターゲットファイルの名前、optionsは動作を指定するため
の0個以上のオプションパラメータです。1つのoptionは、マイナス記号(\-)とそ
れに続く文字列から成ります。filenamesとoptionsはスペースかタブで区切って
指定しますが、optionsはマイナス記号(\-)に続けて複数連結して指定することも
できます。optionsのデフォルトはUNIXでは\-e、MS-DOSでは\-sです。ターゲット
ファイルを1個も指定しない場合、標準入力から入力し標準出力に出力するフィル
タとして動作します。
.PP
QKC C Versionにはnkfと同等の動作をするnkfエミュレーションモードがありま
す。nkf Version 1.4のほとんどの機能をサポートしていま
す。optionsとfilenamesはnkfの指定方法に準じます。各オプションの意味につい
ては、nkfのドキュメントを参照して下さい。
.br
    alias nkf 'qkc \-nkf'
.br
としてご利用されることをお勧めします。
.SH 【オプション】
.TP
.B \-s
シフトJISコードに変換します。
.TP
.B \-e
EUCに変換します。
.TP
.B \-j
JISコードに変換します。
.TP
.B \-bj
JISコードに変換します。ただし、\-jオプション時とは違うエスケープシーケン
スが使われます。
.TP
.B \-oj
旧JISコードに変換します。
.TP
.B \-nj
NEC JISコードに変換します。
.TP
.B \-is
入力ファイルの漢字コードをシフトJISコードとみなします。
.TP
.B \-ie
入力ファイルの漢字コードをEUCとみなします。
.TP
.B \-ij
入力ファイルの漢字コードをJISコードとみなします。
.TP
.B \-O
元のファイルは書き換えずに、標準出力(stdout)に出力します。標準出力がファ
イルにリダイレクトされているときは自動的にこのオプションが指定されている
とみなします。
.TP
.B \-I
標準入力(stdin)から入力します。ターゲットファイルが指定されていないときは
自動的にこのオプションが付加されます。このオプションを指定すると、自動的
に\-Oオプションも指定されたものとして、出力先は標準出力になり、フィルタと
して動作します。
.TP
.B \-m
改行コードをCR LF(0Dh 0Ah)にします。
.TP
.B \-u
改行コードをLF(0Ah)にします。
.TP
.B \-ma
改行コードをCR(0Dh)にします。
.TP
.B \-7
7ビットJISコードを指定します。7ビットJISコードとは、半角カナ文字の最上位
ビットを0にマスクすると共に前後にSO(0Eh)、SI(0Fh)コードが挿入されているコー
ドのことです。なお、このオプションは、\-j, \-bj, \-oj, \-njオプションのい
ずれかが指定されているとき、あるいは入力側がJISコードのときに有効です。
.TP
.B \-z
ファイルの最後に^Zが付いている場合^Zを取り除きます。UNIXで出力先が標準出
力の場合、このオプションは無視されます。
.TP
.B \-q
エラーメッセージ以外の情報の表示を抑制します。
.TP
.B \-h
書式と主要なオプションの要約を示すヘルプ画面を表示します。
.TP
.B \-H
書式とオプションの要約を示すヘルプ画面を表示します。
.SH 【環境変数】
環境変数 QKC に定常的に使用するオプションのリストを登録しておくことができ
ます。環境変数 QKC に登録されているオプションは、実際のコマンドライン引数
の前に挿入されて処理されます。
.SH 【関連事項】
nkf(1)
.SH 【作者】
東京大学工学部電子情報工学科
.br
佐藤公彦(K.Sato)
.br
NIFTY-Serve : JBG03513
.br
PC-VAN      : FDF90332
.br
Internet    : sato@sail.t.u-tokyo.ac.jp
.SH 【バグ】
現在の仕様では、リンクしたファイルを変換すると、変換後同名の通常ファイル
が作成され、リンクは失われます。リンクしたファイルに対する処理は現在検討
中です。
